### ISSUE TITLE
The requested address is not valid in its context

### ISSUE THREAD

**Issue by UiharuKazari2008** [VolcanicArts/VRCOSC#160]
Im getting this error when ever it starts its forwaring to my routed devices but I dont know what its requesting that it cant get

```
2024-03-05 04:04:53 [verbose]: AppManager state changed to Started
2024-03-05 04:05:35 [verbose]: Performing save for file router.json
2024-03-05 04:05:38 [verbose]: Performing save for file router.json
2024-03-05 04:05:38 [verbose]: Performing save for file router.json
2024-03-05 04:05:41 [verbose]: Performing save for file router.json
2024-03-05 04:05:42 [verbose]: AppManager state changed to Stopping
2024-03-05 04:05:42 [verbose]: AppManager state changed to Stopped
2024-03-05 04:05:42 [verbose]: AppManager state changed to Starting
2024-03-05 04:05:42 [error]: The requested address is not valid in its context.
2024-03-05 04:05:42 [error]: System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
2024-03-05 04:05:42 [error]: at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2024-03-05 04:05:42 [error]: at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
2024-03-05 04:05:42 [error]: at System.Net.Sockets.Socket.Bind(EndPoint localEP)
2024-03-05 04:05:42 [error]: at VRCOSC.Game.OSC.Client.OscReceiver.Enable()
2024-03-05 04:05:42 [error]: OscReceiver experienced an exception
2024-03-05 04:05:42 [error]: System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
2024-03-05 04:05:42 [error]: at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2024-03-05 04:05:42 [error]: at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
2024-03-05 04:05:42 [error]: at System.Net.Sockets.Socket.Bind(EndPoint localEP)
2024-03-05 04:05:42 [error]: at VRCOSC.Game.OSC.Client.OscReceiver.Enable()
2024-03-05 04:05:42 [verbose]: AppManager state changed to Started
```

**Comment by VolcanicArts** [comment]
Please join the Discord server and open a support thread and post your router setup
