### ISSUE TITLE
WindowsMediaProvider causes Chrash

### ISSUE THREAD

**Issue by ROBdk97** [VolcanicArts/VRCOSC#161]
Application: VRCOSC.exe
CoreCLR Version: 6.0.2824.12007
.NET Version: 6.0.28
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The Device is not ready. (0x80070015)
   at VRCOSC.Game.Providers.Media.WindowsMediaProvider.onCurrentSessionChanged(GlobalSystemMediaTransportControlsSessionManager _, CurrentSessionChangedEventArgs _2)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass141_0.<abortExecutionFromException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.processFrame()

May take a look myself. 
Not sure what is causing the issue. Playing Music from Plex via Chrome as it does not pick up Plexamp.

**Comment by VolcanicArts** [comment]
Seems like a race condition based on Windows not initialising the source in time for when VRCOSC wants to access the data. Some media sources are a bit iffy with providing their media data to the Windows media service
